tic_tac_toe/config/routes.rb
TicTacToe::Application.routes.draw do
  get 'login', to: "sessions#new"

  resources :sessions, only: [:new, :create, :destroy]

  resources :users

  resources :games

  resources :index, only: [:index]

  resources :about, only: [:index]

  root :to => 'users#index'

end

tic_tac_toe/app/views/layouts/_login.html.erb
<h1>Login</h1>
  <%= form_tag sessions_path do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <%= submit_tag "Log in" %>
    </div>
  <% end %>

  

tic_tac_toe/app/views/layouts/_navbar.html.erb
 <ul class ='nav_bar'>
    <li><%= link_to 'All Users', users_path %></li>
    <li><%= link_to 'Register', new_user_path %></li>
    <li><%= link_to 'About', about_index_path %></li>
    <li><%= link_to 'New Game', new_game_path %></li>
  </ul>

tic_tac_toe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <%= favicon_link_tag "favicon.io" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Patrick+Hand+SC' rel='stylesheet' type='text/css'>
</head>
<body>

<h1><%= link_to 'Tic Tac Toe', users_path %></h1>

<p><% if current_user %>
   <p> Hello, <%= current_user.name %> </p>
   <%= link_to 'Logout', session_path(session), method: :delete, data: {confirm: "Are you sure?"} %></p>
<% end %>

<nav>
 <%= render 'layouts/navbar' %>
</nav>

<%= yield %>




</body>
</html>